name: Publish Central
on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Set LIBRARY_VERSION
        run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "LIBRARY_VERSION=${TAG#v}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Run tests
        run: ./mill test

      - name: Publish
        run: ./mill mill.javalib.SonatypeCentralPublishModule/
        env:
          MILL_PGP_PASSPHRASE: ${{ secrets.MILL_PGP_PASSPHRASE }}
          MILL_PGP_SECRET_BASE64: ${{ secrets.MILL_PGP_SECRET_BASE64 }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.MILL_SONATYPE_PASSWORD }}
          MILL_SONATYPE_USERNAME: ${{ secrets.MILL_SONATYPE_USERNAME }}
